export default {
	NOTIFICATION_ON: "GENERAL_NOTIFICATION_ON",
	NOTIFICATION_OFF: "GENERAL_NOTIFICATION_OFF",

	TOUCHID_ON: "GENERAL_TOUCHID_ON",
	TOUCHID_OFF: "GENERAL_TOUCHID_OFF",

	TYPES: "GENERAL_TYPES",
	SETTING_WHATSAPP: "SETTING_WHATSAPP",

	REDIRECT_TO: "GENERAL_REDIRECT_TO",

	USER_SEARCH: "GENERAL_USER_SEARCH",

	WELCOME_SKIP: "GENERAL_WELCOME_SKIP",
	TERMS_SKIP: "GENERAL_TERMS_SKIP",

	MENUS: "GENERAL_MENUS",

	FAST_LOGIN: "GENERAL_FAST_LOGIN",

	SAVE_FAQ_SEARCH: "GENERAL_SAVE_FAQ_SEARCH",
	REMOVE_FAQ_SEARCH: "GENERAL_REMOVE_FAQ_SEARCH",


	SAVE_FILTERS: "GENERAL_SAVE_FILTERS",
};
